### ISSUE TITLE
例题6.7代码的一个修改意见

### ISSUE THREAD

**Issue by fizherbeart** [BenedictYoung/Lecture#3]
https://github.com/BenedictYoung/Lecture/blob/c9413ca0771335a70375bb7e43e6069486b1c87a/Chapter6/6.7.cpp#L18
这里不用加1应该也可以，向下取整就够用了，您的书上代码也是没有加1的。

**Comment by BenedictYoung** [comment]
虽然这道题目可以这么做，但是建议加1，因为如果遇到x = y^2，开根号之后的结果是浮点数，由于浮点数的精度问题，不一定能保证取下整一定是y。

**Comment by zebangyang** [comment]
嗯嗯，不加1也是可以的。
